#!/usr/bin/env ruby

require 'optparse'
require 'yaml'
require 'json'

require_relative 'lib/moxible'
require_relative 'lib/option_parser'
require_relative 'lib/settings'

globalParser = MoxibleOptionParser::Builder::initializeGlobalParser
globalParser.order!
command, options = MoxibleOptionParser::Parser::parse globalParser, ARGV
quest = Moxible::Settings::createQuest command, options
result = MoxibleRunner::Runner::run quest
MoxiblePrinter::Printer::printResult result
